---
language: ruby
script: "bundle exec rubytest -v -Ilib test/"
bundler_args: --without guard
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - rbx
  - jruby
  - ree
matrix:
  allow_failures:
    - rvm: rbx
cache: bundler
