--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Delete multiple values from array.
- !ruby/struct:RDoc::Markup::Flow::VERB 
  body: "  a = [1,2,3,4]\n  a.delete_values(1,2)   #=&gt; [1,2]\n  a                      #=&gt; [3,4]\n"
- !ruby/struct:RDoc::Markup::Flow::P 
  body: "CREDIT: Trans"
full_name: Array#delete_values
is_singleton: false
name: delete_values
params: (*values)
visibility: public
